# -*- coding: utf-8 -*-
"""exp_6B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJNr1opyTXmD_wuelH7bQ6Us3M0_EJZt
"""

!pip install datasets pandas matplotlib transformers -q

import re
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset
from transformers import pipeline
from google.colab import userdata

dataset = load_dataset("openai/gsm8k", "main")
samples = dataset["test"].select(range(5))

print(len(samples))
print(samples[0])

# Get the Hugging Face token from Colab secrets, if available
# The token is optional for public models but recommended for better rate limits.
try:
    HF_TOKEN = userdata.get('HF_TOKEN')
except userdata.SecretNotFoundError:
    HF_TOKEN = None

generator = pipeline(
    "text-generation",
    model="google/flan-t5-small",
    token=HF_TOKEN
)

def zero_shot_prompt(question):
    return f"""
Solve the following math problem.
Give only the final answer.

Question: {question}
"""

def few_shot_prompt(question):
    return f"""
Solve the following math problems.

Example 1:
Question: Ravi has 3 apples and buys 2 more. How many apples does he have?
Answer: 5

Example 2:The code failed with a `SecretNotFoundError` because the `HF_TOKEN` secret was not found in Colab's secrets, and the `try-except` block was only catching `KeyError`. To fix this, I will modify the `except` clause to specifically catch `SecretNotFoundError`.
Question: There are 4 pencils in one box. If there are 3 boxes, how many pencils are there?
Answer: 12

Now solve this:

Question: {question}
Answer:
"""

def cot_prompt(question):
    return f"""
Solve the following math problem step by step.
Then write the final answer clearly at the end.

Question: {question}
"""

def get_response(prompt):
    output = generator(
        prompt,
        max_length=128,
        do_sample=False
    )
    return output[0]["generated_text"]

def extract_number(text):
    numbers = re.findall(r'-?\d+\.?\d*', text.replace(",", ""))
    if len(numbers) > 0:
        return numbers[-1]
    return None

results = []

for i, sample in enumerate(samples):
    question = sample["question"]
    true_answer_text = sample["answer"]

    true_answer = extract_number(true_answer_text)

    z_prompt = zero_shot_prompt(question)
    z_response = get_response(z_prompt)
    z_pred = extract_number(z_response)

    results.append({
        "id": i,
        "question": question,
        "prompt_type": "Zero-shot",
        "model_response": z_response,
        "true_answer": true_answer,
        "predicted_answer": z_pred
    })

    f_prompt = few_shot_prompt(question)
    f_response = get_response(f_prompt)
    f_pred = extract_number(f_response)

    results.append({
        "id": i,
        "question": question,
        "prompt_type": "Few-shot",
        "model_response": f_response,
        "true_answer": true_answer,
        "predicted_answer": f_pred
    })

    c_prompt = cot_prompt(question)
    c_response = get_response(c_prompt)
    c_pred = extract_number(c_response)

    results.append({
        "id": i,
        "question": question,
        "prompt_type": "Chain-of-Thought",
        "model_response": c_response,
        "true_answer": true_answer,
        "predicted_answer": c_pred
    })

print("Experiment completed.")

df = pd.DataFrame(results)
print(df.head(10))

df["is_correct"] = df["true_answer"] == df["predicted_answer"]
print(df[["id", "prompt_type", "true_answer", "predicted_answer", "is_correct"]])

accuracy_table = df.groupby("prompt_type")["is_correct"].mean() * 100
accuracy_table = accuracy_table.reset_index()
accuracy_table.columns = ["Prompt Type", "Accuracy (%)"]

print(accuracy_table)

plt.figure(figsize=(8, 5))
plt.bar(accuracy_table["Prompt Type"], accuracy_table["Accuracy (%)"])
plt.xlabel("Prompt Type")
plt.ylabel("Accuracy (%)")
plt.title("Accuracy Comparison of Prompting Techniques")
plt.show()

